### ISSUE TITLE
ISETBIO validations

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#145] opened 2016-08-08 10:30 UTC
Due to some major changes in ISETBIO, there are a number of validation scripts that fail to validate against previous ground truth data.

Some of these failures are due to changes in the internal structure of the various objects. This issue will be addressed next. However, other failures are due to numerical differences in the computed properties which are way above the residual magnitudes that were satisfied in earlier versions of ISETBIO.

I will be posting these findings below, for discussion.

**Wavefront validation scripts** 4/5 (listed below) fail due to numerical issues in the 'conePsfInfo.T' field:
```
[24] v_wvfComputeConePSF: FAILS
[25] v_wvfDiffractionPSF: FAILS
[26] v_wvfSpatialSampling: PASSES
[27] 'v_wvfStilesCrawford: FAILS
[28] 'v_wvfZernikePolynomials: FAILS
```

Below is a depiction of the differences for 'v_wvfZernikePolynomials':
<img width="1121" alt="wavefrontfailure" src="https://cloud.githubusercontent.com/assets/3444212/17476792/87963250-5d6a-11e6-8518-0fc7f38cbf1d.png">

Same effects are seen in the other wavefront tutorials. 

All of the above tutorials can be made to pass by validating against much lower residual magnitudes: **`5*1e-4 versus 1e-11`** which was used successfully with earlier versions of ISETBIO.

I am waiting for confirmation that this change in residual margins is OK before I proceed with updating the scripts. Or perhaps there is something else going on that needs further investigation.

**Comment by npcottaris** [comment] 2016-08-08 11:35
Similar observations for 'v_stockman2xyz'. The script passes only after setting the following residual margins:
```
T_cones: 0.0005
T_cones_ss2: 0.005
T_ptbData: 0.0005
ptbPred: 0.0015
```
Again, these validations were passing with residual margins set to 1e-11, in earlier versions of ISETBIO.

**Comment by DavidBrainard** [comment] 2016-08-08 11:57
This one is probably due to the fact that I updated the PTB Stockman-Sharpe fundamentals to use all the decimal places available.  The previous version was rounded to two places.  There was something I was doing where the rounding was bugging me, even though I don't believe that the underlying data are good to all the places they specify the fundamentals to.

I'll take a closer look and then I think we can update the validation files without changing the tolerance.

**Comment by DavidBrainard** [comment] 2016-08-08 13:12
I looked at this one.  Just update the validation files for the current code, it is running OK with respect to the way the plots look and the internal validations pass.
And we have a theory that explains why there is a difference to the stored validations.

**Comment by DavidBrainard** [comment] 2016-08-08 13:42
For grins, can you go back to a version of isetbio close to the one for which the validation data were written and try these?  We saw something like this with the display scripts before we updated to the cone mosaic branch, and attributed to some numerical change within Matlab, or some such, but there the change in tolerance needed was much smaller.

If we see these same sorts of failures with roughly the same isetbio code used to produce the validations, it would tell us whether the change is in our isetbio code or outside of it.

If I'm reading the graphs correctly, a tolerance of 1e-4 corresponds to roughly 5 parts in 10,000 since the PSF runs between 0 and 1. That much difference is not of any biological significance, but it is a bit weird to me that it would crop up, since it is very large compared to computer precision.

**Comment by npcottaris** [comment] 2016-08-08 13:44
**Internal validation failures**

The following 4 scripts fail the internal validation tests in what appears to be fairly significant ways:

**`v_cones`** fails internal validation  in 2 tests:
 - Difference between PTB and isetbio lens transmittance differs from zero by more than tolerance (1e-12). **[Diff: 0.982817]**
 - Difference between PTB and isetbio cone quantal efficiency differs from zero by more than tolerance (0.001). **[Diff: 0.300826]**

**`v_DisplayColorConversion`** fails internal validation in 3 tests:
 - L isomerization comparison differs from zero by more than tolerance (0.01). **[Diff: 0.236902]**
 - M isomerization comparison differs from zero by more than tolerance (0.01). **[Diff: 0.272147]**
 - S isomerization comparison differs from zero by more than tolerance (0.01). **[Diff: 0.842823]**

**`v_HumanRetinalIlluminance580nm`**  fails internal validation in 1 test:
 - Irradiance (q/sec/m^2/nm) at 580 nm = 8.68243e+18, Expected = 1e+19, Residual = -13.1757 % differs from zero by more than tolerance (0.03). **[Diff: 0.131757]**

**`v_IrradianceIsomerizations`** fails internal validation in 3 tests:
  - Spatial uniformity of optical image irradiance differs from zero by more than tolerance (0.01). **[Diff: 1.32152]**
  - Difference between PTB and isetbio irradiance differs from zero by more than tolerance (0.01). **[Diff: 57.6373]**
  - Difference between PTB and isetbio quantal efficiencies differs from zero by more than tolerance (0.01). **[Diff: 2.38265]**

**Comment by npcottaris** [comment] 2016-08-08 13:51
Yes, you are reading the graphs correctly, it is a small effect. But like you say, it is a bit alarming that we now have to allow for such a large residual allowance now but not before.


On Aug 8, 2016, at 4:42 PM, David Brainard <notifications@github.com<mailto:notifications@github.com>> wrote:

If I'm reading the graphs correctly, a tolerance of 1e-4 corresponds to roughly 5 parts in 10,000 since the PSF runs between 0 and 1. That much difference is not of any biological significance, but it is a bit weird to me that it would crop up, since it is very large compared to computer precision.

**Comment by npcottaris** [comment] 2016-08-08 13:52
By the way, I am conducting all these tests in the master branch.

**Comment by DavidBrainard** [comment] 2016-08-08 13:52
I have lost track of what has been merged with what.  If I want to look at and tinker with these validations, should I be on the master branch or the hexdensity branch?

**Comment by npcottaris** [comment] 2016-08-08 13:55
Just happened to answer your question at the same time as you posted it: I am doing these tests on the master branch.

**Comment by DavidBrainard** [comment] 2016-08-08 14:08
For v_cones (which is v_Cones on my system and on gitHub -- you need to fuss a little to fix those case errors because the git client doesn't recognize a case difference as real), I think the error arises because the lens
is now in the oi object, not in the lens.  See IBIOColorDetect/t_colorGaborScene for how to get it.  Indeed, lensGet is now deprecated.

I think the thing to do is switch this validation over to use the optical image and coneMosaic objects.  If you get the lens transmittance out of the oi object and multiply by the cone qe from the cone mosaic object, I think you should match the PTB values.

I think if we rewrite and get everything to agree with the PTB values in the current validation script, we would be satisfied.  I don't think any of the PTB stuff has changed.

**Comment by npcottaris** [comment] 2016-08-08 14:09
**`osBiophys`** validation failures

The 'v_osBioPhysObject' scripts fails validation  in two major ways as illustrated by the attached diff plots below.
In the diff plot below, the stimulus has opposite polarity in the ground truth vs the validation data !!

![biophysobj](https://cloud.githubusercontent.com/assets/3444212/17482434/6fee5162-5d8a-11e6-958f-e220622a1fbb.png)

In the second diff plot below, there are clear differences in the dynamics of the eye movement induced photocurrent responses.

![biophysobj2](https://cloud.githubusercontent.com/assets/3444212/17482444/78db700c-5d8a-11e6-8746-2b17e2436304.png)

Not sure when either of these happened, but unless someone has a better idea of why this may be, we would have to go back in time and see which commit is to be blamed. Sigh !

**Comment by npcottaris** [comment] 2016-08-08 14:20
The 'v_sceneExamples' script fails validation in a major way only for the harmonic scene. 
```
[data mismatch  1]   : Max difference between 'groundTruthData.harmonic.data.knownReflectance' and 'validationData.harmonic.data.knownReflectance' (31) is greater than the set tolerance (1e-11). See figure named: ''groundTruthData.harmonic.data.knownReflectance' vs. 'validationData.harmonic.data.knownReflectance''
[data mismatch  2]   : Max difference between 'groundTruthData.harmonic.data.photons' and 'validationData.harmonic.data.photons' (7.68195e+15) is greater than the set tolerance (1e-11). See figure named: ''groundTruthData.harmonic.data.photons' vs. 'validationData.harmonic.data.photons''
[data mismatch  3]   : Max difference between 'groundTruthData.harmonic.illuminant.data.photons' and 'validationData.harmonic.illuminant.data.photons' (9.23525e+12) is greater than the set tolerance (1e-11). See figure named: ''groundTruthData.harmonic.illuminant.data.photons' vs. 'validationData.harmonic.illuminant.data.photons''
```
 	
This is most likely because we changed the harmonic scene to have an origin at the middle of the scene vs the top left.

**Comment by DavidBrainard** [comment] 2016-08-08 14:25
Yes, as long a that looks plausible when you look at what it produces, I'd go ahead and re-write the validation data for this one and call it good.

DB

**Comment by npcottaris** [comment] 2016-08-08 14:32
**v_oi** fails validation for two reasons: 
  - different structure of the oi struct (expected), 
  - but also major differences in some validation data, e.g.

```
[data mismatch  4]   : Max difference between 'groundTruthData.humanOIFromScene.data.illuminance' and 'validationData.humanOIFromScene.data.illuminance' (1.20164) is greater than the set tolerance (1e-11). See figure named: ''groundTruthData.humanOIFromScene.data.illuminance' vs. 'validationData.humanOIFromScene.data.illuminance''
[data mismatch  5]   : Max difference between 'groundTruthData.humanOIFromScene.data.photons' and 'validationData.humanOIFromScene.data.photons' (1.37923e+14) is greater than the set tolerance (1e-11). See figure named: ''groundTruthData.humanOIFromScene.data.photons' vs. 'validationData.humanOIFromScene.data.photons''
```

![oidata](https://cloud.githubusercontent.com/assets/3444212/17483136/9165f48c-5d8d-11e6-8832-8a5ce54a089b.png)

Finally, **v_diffuser** fails validation due to different structure of the oi struct (expected).

**Comment by npcottaris** [comment] 2016-08-08 14:38
That's exatctly what it looks like.

On Aug 8, 2016, at 5:25 PM, David Brainard <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes, as long a that looks plausible when you look at what it produces, I'd go ahead and re-write the validation data for this one and call it good.

DB

**Comment by fmrieke** [comment] 2016-08-08 14:48
That is odd.  I would suspect something in the init parameters got changed as everything seems quite off.  The ground truth data looks correct (i.e. right polarity for decrement).  The “default” parameters in osInit.m are given in the comments.

Fred

**Comment by DavidBrainard** [comment] 2016-08-08 15:55
I think the null hypothesis with v_oi is that the lens transmission is causing the difference in the oi.  You can turn that off.  See v_colorGaborScene in IBIOColorDetect.  If turning lens off makes current image agree with ground truth, then turn it back on and re-write the validation data, as I would say that we understand the reason.

**Comment by npcottaris** [comment] 2016-08-08 18:59
Reversing PTB repo eight before July 1 (when the ground truth data were written) makes the various wvf validations pass.
This is also right before you made the changes in the cone spectra.

This makes sense since the failures were all in the 'conePsfInfo.T' field.
So I will go ahead and regenerate ground truth for all the wavefront scripts.

Nicolas


On Aug 8, 2016, at 4:42 PM, David Brainard <notifications@github.com<mailto:notifications@github.com>> wrote:

For grins, can you go back to a version of isetbio close to the one for which the validation data were written and try these? We saw something like this with the display scripts before we updated to the cone mosaic branch, and attributed to some numerical change within Matlab, or some such, but there the change in tolerance needed was much smaller.

**Comment by DavidBrainard** [comment] 2016-08-08 19:14
Are the scripts rreading in the Stockman-Sharpe fundamentals?  In that case, it makes perfect sense that those validations would be a little off in the T field, and I guess a PSF that integrated over cone sensitivities would also be a little different.

Great.  Bit by bit!

**Comment by npcottaris** [comment] 2016-08-08 19:29
Yup, they do, either directly or indirectly, i.e., via wvfCreate.

N.


On Aug 8, 2016, at 10:14 PM, David Brainard <notifications@github.com<mailto:notifications@github.com>> wrote:

Are the scripts rreading in the Stockman-Sharpe fundamentals? In that case, it makes perfect sense that those validations would be a little off in the T field, and I guess a PSF that integrated over cone sensitivities would also be a little different.

Great. Bit by bit!

**Comment by DavidBrainard** [comment] 2016-08-09 12:15
One thing to check on this is whether the input to os calculation passes through an oi.  If so, then the insertion of the lens will change the input to the os calculation, which might explain the differences.  Particularly if the pre-stimulus level was hard coded to be the mean of what used to be the input.  If it looks like this might be the case, the check would be to take the lens out of the os object, which should restore the calculation through the sensor to the way it used to be.

**Comment by jamesgolden1** [comment] 2016-08-17 19:56
For v_osBioPhysObj.m, I fixed a couple of lines so the decrement stimulus is actually decrementing. Unfortunately, it still does not pass the fast validation. It seems as if the problem is not being caused by oi/lens, either.

@npcottaris it seems that the v_osBioPhysLightIncrementDecrement is a more sophisticated version of the increment/decrement code - were you planning to deprecate the v_osBioPhysObject once you were satisfied with the individual files?

**Comment by npcottaris** [comment] 2016-08-17 21:17
Yes, the increment/decrement error is gone. Good catch. 

The failure that remains is not just in the FAST but also in the FULL data, and it is caused by the significant differences in response dynamics between validation and ground truth (see below). 

To find the source of this discrepancy, we have to look back in history to find if any os parameters were changed, as Fred suggested.

<img width="1137" alt="dynamics" src="https://cloud.githubusercontent.com/assets/3444212/17753526/2a9084f8-649e-11e6-858a-001e35c572b7.png">

**Comment by jamesgolden1** [comment] 2016-08-17 22:20
There was a some sort of mismatch in the time step for that particular section - it was using 1e-4 sec when it should have been using 5e-5 sec. v_osBioPhysObject.m now passes the FAST and FULL validations.

**Comment by npcottaris** [comment] 2016-08-17 22:33
Great. Thanks James!

**Comment by DavidBrainard** [comment] 2016-08-18 12:42
I'm a little confused.  I thought James said the validation passes, but Nicolas indicates that it fails.  Is the same code producing significantly different results on two computers, or are we talking about two different validation scripts?

**Comment by npcottaris** [comment] 2016-08-18 12:49
Here is what happened. The validation was failing on two components. I said it was still failing on the second component after James fixed the first component. Then James fixed the second component as well, and now the script passes everything.

**Comment by DavidBrainard** [comment] 2016-08-18 12:53
Excellent!

**Comment by wandell** [comment] 2016-09-09 00:41
Seems like this has been resolved by @npcottaris recent updates to the validation script.  We are aware of only two apparently small things that remain.  One is some validation on v_DisplayColorConversion (which runs and is accurate but doesn't match the validation data) and v_osLinearObject.

We think this issue is basically resolved, but we will open two smaller issues to stay focused on those validation scripts.

**Closed by wandell** 2016-09-09 00:41 UTC
