### ISSUE TITLE
v_osLinearObject does not match validation data

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#155] opened 2016-09-09 00:43 UTC
We think this might be something that @jamesgolden1 changed in os.compute.  He is on it.

**Comment by DavidBrainard** [comment] 2016-09-09 12:59
For me, this passes on the full data and fails on the fast.  If that is the behavior you see, then probably the problem is a tolerance issue in how we compute the fast dataset.

I am wondering whether we should abandon the fast validation idea.  It seemed clever at the time, but it has to date caused vastly more headaches than it has solved.  The issue is that it is very brittle to small numerical changes.  Maybe that is now fixed or fixable.

The original idea was that the validation files could be compact, but we've solved that issue with the remote data toolbox.  And I think the actual full comparisons are a small fraction of the validation time, which is dominated by compute time for our validation set.

Maybe we are close enough to the goal line that we should just get this working, but let's keep in mind that we could abandon it.

**Comment by npcottaris** [comment] 2016-09-09 15:20
For me, all validations pass FAST and FULL on 3 different machines, all running ElCapitan and Matlab 2015b.

Funny !

**Comment by DavidBrainard** [comment] 2016-09-09 15:29
I am running 2016a on a pretty new iMac.  We observed previously this type of numerical difference across machines.  Given how einsy these differences are in a fractional sense, I think we ought to increase the tolerance used for this validation and move on.  It might be nice to be able to specify the tolerance as a fraction of the smaller of the absolute value of the two values being compared.

**Comment by wandell** [comment] 2016-09-09 15:43
That would be fine with me.  

Any diagnosis of what I am doing wrong so that validations fail with this error (which I placed on the UnitTest repository, I think).

Error using UnitTest/initializeUnitTest (line 43)
Java exception occurred:
java.net.UnknownHostException: Macula: Macula: nodename nor servname provided, or not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1473)
Caused by: java.net.UnknownHostException: Macula: nodename nor servname provided, or not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)

Error in UnitTest (line 123)
            obj.initializeUnitTest();

Error in UnitTest.runValidationSession>validateFull (line 87)
    UnitTestOBJ = UnitTest();

Error in UnitTest.runValidationSession (line 30)
        validateFull(vScriptsList);

Error in ieValidateFullAll (line 80)
UnitTest.runValidationSession(vScriptsList, 'FULL');

**Comment by npcottaris** [comment] 2016-09-21 19:23
v_osLinearObject` should now pass all validations. This was achieved by setting a custom tolerance (1e-7) for fields `adaptedCur3`, and `osAdaptedCur3`. This change should be incorporated in the osvalidation branch.

Please git pull your copy of master and validate this script to ensure it passes on your machines, and if it does, lets close this issue.

**Comment by jamesgolden1** [comment] 2016-09-21 19:53
Thanks Nicolas, works for me. I have merged our ovalidation branch locally
and all the validations look good. I will push to master by 115 pacific
time.

**Comment by npcottaris** [comment] 2016-09-21 19:58
Great, thanks. Closing this issue now.

**Closed by npcottaris** 2016-09-21 19:58 UTC
