### ISSUE TITLE
Cone spacing as a function of eccentricity

### ISSUE THREAD

**Issue by jamesgolden1** [isetbio/isetbio#84] opened 2015-09-14 21:13 UTC
A few weeks ago, David mentioned that he had code based on data from the Sloan to specify cone spacing as a function of the eccentricity. I am interested in implementing this, as it is important for both future RGC simulations and Fred's color Gabor detection experiment with Greg Horwitz. 

The spacing of cones in the sensor object is set by sensorSetSizeToFOV.m. There are also width/height and widthgap/heightgap properties of 'pixel', but the number of cones in the sensor is set before these can be set (as far as I can tell). I wanted to start this issue to allow for any thoughts or comments on how this ought to be implemented. I have a quick and messy calculation based on Fig. 3 from the paper below and I am working on incorporating this into sensorSetSizeToFOV.m.

Here is the paper:
https://www.cis.uab.edu/sloan/ScienceCover/Curcio_Science1987.pdf

**Comment by DavidBrainard** [comment] 2015-09-15 16:13
I will move my code for this into isetbio within the next few days.

In the meantime, we *really* need to get the outersegment object moved into the master branch, and to remove the older way of calling the code.  I am concerned that more and more is getting built on the older code and that the transition is just going to get more difficult with every day that we don't make the switch.

**Comment by wandell** [comment] 2015-09-15 18:38
OK with me.  I think mainly HJ will have to take notice, but he seems to me to be on top of the situation.

Maybe I should take this moment to ask for us to list a set of things to check off as we merge the new object into the flow.

do you feel the documentation of the method is in good shape?
Are there tutorial scripts that illustrate the basic calling cases?
Are the older scripts updated to be compliant with the new object?
Perhaps there is some regression testing in the validation code  as we make the shift?

I am sure you have all the unit testing under control.

Anyway, IMHO go for it.  This is not a stressful time.

Brian

On Sep 16, 2015, at 1:13 AM, David Brainard <notifications@github.com<mailto:notifications@github.com>> wrote:


I will move my code for this into isetbio within the next few days.

In the meantime, we really need to get the outersegment object moved into the master branch, and to remove the older way of calling the code. I am concerned that more and more is getting built on the older code and that the transition is just going to get more difficult with every day that we don't make the switch.

—
Reply to this email directly or view it on GitHub<https://github.com/isetbio/isetbio/issues/84#issuecomment-140447636>.

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by jamesgolden1** [comment] 2015-09-15 18:59
I just pushed final changes to the outersegment branch, so it is ready to
be merged into the master. I will check with HJ before the merge.

There is more to be done on the documentation, which I will put some time
into. I believe the class, subclasses, and their methods are appropriately
documented in terms of headers and comments, and I will add a section to
the Wiki on the 'Architecture' page.

There is a basic tutorial, t_OuterSegmentClasses, but it may be useful to
create a slightly longer version.

In terms of older scripts, the main issue will be changing calls to
'coneAdapt' to a couple of lines initializing an os object and calling
'osCompute'. My apologies for taking so much time on the os object and
causing coneAdapt to be squashed and then reincarnated. Additionally, I
renamed all 'rieke*' functions to 'os*' in the isettools/outersegment/util
folder. I do yet not have an answer for the validation testing.

**Comment by hjiang36** [comment] 2015-09-15 20:40
I'm ready for the merge. I used the os object in some scripts and they look good to me. We might need to update documents, tutorials, validations, etc. But seems like we can do that after the merge.

I will check again and see if there's some old scripts/functions calling coneAdapt. I think it might be a good idea to have a coneAdapt.m that gives a error and describes what's the new way to update the code. It could be in some deprecated folder and get removed after one or two month.

Having cone density as a function of eccentricity is great. But we should do more test before using it seriously. With this change, we will have cone spacing not equal to the cone diameter and we need to check if our computing routine uses the right one. For example, spatialIntegration.m uses sensor pixel area to do the spatial scaling, which includes all the gap between cones (currently, gap is 0). But anyway, I would like to help do this change. Maybe, I could work with JG on it in the coming week.

Also, I think it's better to build eccentricity into the system, not as a standalone function. That is, we could have something like sensorCreate('human', coneCreate, eccentricity). In this, we could handle not only cone density changes, but also cone diameter, macular pigment and etc.

Just my personal idea and let's have more discussion on that.

Thanks
HJ

**Comment by chichilnisky** [comment] 2015-09-15 20:45
Great.

My only comment is to remember what I’ve said in a few of these conversations: not *eccentricity*, but *visual field location*.

The former is 1D, the latter is a 2D quantity.  We need the latter because the retina is not radially homogeneous.

ej

On Sep 15, 2015, at 4:40 PM, Haomiao Jiang <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm ready for the merge. I used the os object in some scripts and they look good to me. We might need to update documents, tutorials, validations, etc. But seems like we can do that after the merge.

I will check again and see if there's some old scripts/functions calling coneAdapt. I think it might be a good idea to have a coneAdapt.m that gives a error and describes what's the new way to update the code. It could be in some deprecated folder and get removed after one or two month.

Having cone density as a function of eccentricity is great. But we should do more test before using it seriously. With this change, we will have cone spacing not equal to the cone diameter and we need to check if our computing routine uses the right one. For example, spatialIntegration.m uses sensor pixel area to do the spatial scaling, which includes all the gap between cones (currently, gap is 0). But anyway, I would like to help do this change. Maybe, I could work with JG on it in the coming week.

Also, I think it's better to build eccentricity into the system, not as a standalone function. That is, we could have something like sensorCreate('human', coneCreate, eccentricity). In this, we could handle not only cone density changes, but also cone diameter, macular pigment and etc.

Just my personal idea and let's have more discussion on that.

Thanks
HJ

**Comment by fmrieke** [comment] 2015-09-15 21:13
This all sounds good to me.  I will update the cone model validation and demo scripts when everything is merged.

Fred

**Comment by wandell** [comment] 2015-09-15 22:17
A scientific question for Fred ...

As cone apertures scale with visual field position, does the cone response per absorption change?  A peripheral cone might absorb at more than double or even triple the rate of a foveal cone.  Will the photo current levels differ so that the peripheral one response is equivalent to the foveal at twice the absorption rate?  Also, does the outer segment size and amount of photo pigment change?  Or mainly the cross sectional area of the inner segment?

I never wondered this before.  Someone else must have.

B


Stanford

**Comment by DavidBrainard** [comment] 2015-09-16 12:23
OK, great.  What I'm taking from all the above is that we should integrate the OS object into the master branch and then proceed to switch things to use it.  At some point, we should make a tag and delete the alternate code, and then fix anything that breaks at that moment.

**Comment by DavidBrainard** [comment] 2015-09-16 12:25
There will be a little delay in my moving in the mosaic model code.  My computer crashed and burned yesterday -- there are backups but it is taking a while for the systems guys to restore.  The code is actually in my local isetbio repository on the crashed (and backed up) disk, but I can't get to it until it gets restored.  Living homelessly on my laptop for now.

**Comment by fmrieke** [comment] 2015-09-16 13:48
We are worrying about this now!  But currently there is no experimental comparison of cone responses as a function of visual field position.  We see some interesting differences between foveal and peripheral cones - which would suggest that the cone responses will differ substantially (in the wrong direction to correct for differences in absorption rate).  Outer segment volume is not supposed to change much.  

Fred

**Comment by DavidBrainard** [comment] 2015-09-17 12:59
I uploaded the mosaic code to isettools/mosaic.  There is a README.txt file in that directory.  It says:

Notes on mosaic code


The Curcio/Sloan model is for the overall cone packing, without regard to cone type.  It is implemented in the function MakeSloanList, which takes an argument for the number of cones, the number of pixels (given as linear number of pixels for a square image), and the parameters of the model.

The model and how parameters vary with eccentricity is described in: Curcio CA, Sloan KR. 1992. Packing geometry of human cone photoreceptors: variation with eccentricity and evidence for local anisotropy. Visual Neurosci 9: 169-80.

To generate a trichromatic mosaic, the routine is MakeSloanSClist.  This takes the same arguments as MakeSloanList, plus the number of cones that should be S and M.  It generates an overall mosaic, then a mosaic with the same parameters with the number of S cones.  The cones in the overall list that are nearest to the generated S cones are called S.  The rest are allocated between L and M by coin flipping according to the L:M ratio implied by the input parameters.  I just made up this method of generating the overall mosaic, but it seems pretty reasonable.  There may now be better data on the geometry of S cone packing. 

One could think about adding an option to create a tritanopic area in the very central fovea, which I did not do.  That would require working in units of degrees or mm of retina and specifing the size of the tritanopic area.  

As this code gets brought into ISETBIO, we probably do want to make it work in actual units of retinal size, either angle or mm, and make it use a table of parameters taken from the paper.  It is possible that it would be better to specify fraction of S cones rather than number, and L:M ratio rather than number of M cones.  But be careful to round to integer number of cones in a sensible manner, and if there is a tritanopic area to reason about that sensibly.

The output of MakeSloanList is a list of x,y positions.  The output of MakeSloanClist is x,y positions plus an indicator variable (1 -> L, 2 -> M, 3 -> S) giving type of each cone.

This code was written in the early 1990's and was part of a larger toolbox that did various image manipulations related to sampling.  But I think ISETBIO handles most of those, so I have just tried to strip out the key stuff for creating the mosaics.  Matlab had only two-dimensional matrices at the time this was written, so some things may be coded in what seems like a convoluted way given modern Matlab.

**Comment by chichilnisky** [comment] 2015-09-17 13:52
Nice!

Relating to earlier discussions, in terms of infrastructure, I think we should be referring to 2D retinal location (rather than 1D retinal eccentricity) in everything.  I’m a bit concerned that for simplicity we might keep making the eccentricity assumption in the code and this approximation becomes ingrained.

James will be specifying RGC density and properties in terms of 2D retinal location.

I would like to learn how we will handle inter-subject variability in things like cone ratios when we specific a “standard” observer.

ej


On Sep 17, 2015, at 5:59 AM, David Brainard <notifications@github.com<mailto:notifications@github.com>> wrote:


I uploaded the mosaic code to isettools/mosaic. There is a README.txt file in that directory. It says:

Notes on mosaic code

The Curcio/Sloan model is for the overall cone packing, without regard to cone type. It is implemented in the function MakeSloanList, which takes an argument for the number of cones, the number of pixels (given as linear number of pixels for a square image), and the parameters of the model.

The model and how parameters vary with eccentricity is described in: Curcio CA, Sloan KR. 1992. Packing geometry of human cone photoreceptors: variation with eccentricity and evidence for local anisotropy. Visual Neurosci 9: 169-80.

To generate a trichromatic mosaic, the routine is MakeSloanSClist. This takes the same arguments as MakeSloanList, plus the number of cones that should be S and M. It generates an overall mosaic, then a mosaic with the same parameters with the number of S cones. The cones in the overall list that are nearest to the generated S cones are called S. The rest are allocated between L and M by coin flipping according to the L:M ratio implied by the input parameters. I just made up this method of generating the overall mosaic, but it seems pretty reasonable. There may now be better data on the geometry of S cone packing.

One could think about adding an option to create a tritanopic area in the very central fovea, which I did not do. That would require working in units of degrees or mm of retina and specifing the size of the tritanopic area.

As this code gets brought into ISETBIO, we probably do want to make it work in actual units of retinal size, either angle or mm, and make it use a table of parameters taken from the paper. It is possible that it would be better to specify fraction of S cones rather than number, and L:M ratio rather than number of M cones. But be careful to round to integer number of cones in a sensible manner, and if there is a tritanopic area to reason about that sensibly.

The output of MakeSloanList is a list of x,y positions. The output of MakeSloanClist is x,y positions plus an indicator variable (1 -> L, 2 -> M, 3 -> S) giving type of each cone.

This code was written in the early 1990's and was part of a larger toolbox that did various image manipulations related to sampling. But I think ISETBIO handles most of those, so I have just tried to strip out the key stuff for creating the mosaics. Matlab had only two-dimensional matrices at the time this was written, so some things may be coded in what seems like a convoluted way given modern Matlab.

**Comment by jamesgolden1** [comment] 2015-09-17 16:33
David, thank you very much for sharing this code, Haomiao and I will work
on incorporating it. EJ, we will make sure that the input is 2D retinal
location.

On Thu, Sep 17, 2015 at 6:52 AM, E.J. Chichilnisky <notifications@github.com
> wrote:

> Nice!
>
> Relating to earlier discussions, in terms of infrastructure, I think we
> should be referring to 2D retinal location (rather than 1D retinal
> eccentricity) in everything. I’m a bit concerned that for simplicity we
> might keep making the eccentricity assumption in the code and this
> approximation becomes ingrained.
>
> James will be specifying RGC density and properties in terms of 2D retinal
> location.
>
> I would like to learn how we will handle inter-subject variability in
> things like cone ratios when we specific a “standard” observer.
>
> ej
>
>
> On Sep 17, 2015, at 5:59 AM, David Brainard <notifications@github.com

**Comment by wandell** [comment] 2015-09-17 17:25
James,

Please change the name of MakeSloanClist to the usual format.  Something like coneList or coneListSloan or functionalise with coneList('Sloan').

Thanks,
Brian

**Comment by hjiang36** [comment] 2015-09-21 03:51
I made some functions and integrations in the new branch eccentricity. Now, we can create a human sensor at specific retinal location. For example,

    coneP = coneCreate; 
    pos = [5, 0];  % 5 degree eccentricity to the right
    whichEye = 'left'; % left eye
    sensorCreate('human', coneP, pos, whichEye); 

The update achieves desired cone packing density by setting the pixel gaps. Also, sensorCreate adjusts macular pigment optical density according to eccentricity.

The parameters for cone density and macular pigment are slightly adjusted to make sensor with zero eccentricity be exactly the same as ISETBIO original sensor. Through this way, all the existing code should run and produce same result as before.

Up to now, the cone mosaic is still on a rectangular grid. Mosaic code from Brainard provides great model for non-grid cone mosaic, but it hasn't been merged into sensor structure up to this point.

I will check the code with Brian and James next week. If everything looks good, we can merge it back to master afterwards.

Thanks
HJ

**Comment by DavidBrainard** [comment] 2015-09-24 15:13
This sounds good.  The one thing I am not entirely sure is whether the mosaic positions should be part of the cone structure, part of the sensor structure, or even part of a new mosaic structure.  As HJ notes, spectral sensitivity can depend on retinal position, so perhaps having the positions together with the cone spectral sensitivities is correct.

**Comment by jamesgolden1** [comment] 2016-01-06 00:14
Merged the eccentricity branch into master.

**Closed** 2016-01-06 00:14 UTC
