### ISSUE TITLE
coneTemp merge changed sensor image sizes?

### ISSUE THREAD

**Issue by xnieamo** [isetbio/isetbio#41] opened 2015-06-18 19:44 UTC
Using the code before the merge commit, my optical images generated sensor images that were the size 164x164.  Running the same script with the code after the merge results in sensor images the size of 123x123.  

I'm wondering if this was due to some fix introduced in coneTemp or an unintended bug?

**Comment by hjiang36** [comment] 2015-06-18 20:59
Thanks for pointing it out.

I guess it is an unintended bug somewhere. The default sensor size is 72x88 before and after. I think you might change the sensor size within your code somewhere. Could you post some lines of code that gives you 164 (or 123) in size? That could be very helpful to me to find out the bug there.

Thanks
HJ

**Comment by xnieamo** [comment] 2015-06-19 13:47
Yes, I do change the sensor size in my code, but the same code is giving different results.

```
sensor = sensorCreate('human');

sensorRows = sensorGet(sensor, 'rows');
sensor = sensorSet(sensor, 'cols', sensorRows);

sensor = sensorSet(sensor, 'exp time', 0.050);

oi = oiCreate('human');
sensor = sensorSetSizeToFOV(sensor, 0.83, [], oi);

sensor = sensorSet(sensor, 'wavelength', SToWls([380 8 51]));

sensor = sensorSet(sensor, 'noise flag', 0);

oi1 = loadOpticalImageData('Neutral/Standard', 'TestImage0');

s1 = coneAbsorptions(sensor, oi1);

p1 = sensorGet(s1, 'photons');
```
The size of p1 was 164 before the merge and 123 after.

**Comment by hjiang36** [comment] 2015-06-19 17:19
I found that the problem is because some inconsistency between default parameters.
In pixelCreate (line 85), we set cone size to be 2 microns. In the code of sensorCreateConeMosaic.m before merge, the default cone aperture is 1.5 micron. After merge, it uses the cone size from the pixel structure.

In summary, 164 corresponds to 1.5 micron cone aperture and 123 corresponds to 2 micron cones. The after merge code is consistent. The issue now is to determine whether we want a 1.5 micron cone or 2 micron cone. Let's discuss and decide.

If you want to have 164 for now, you can set the pixel size after sensorCreate. I hope this makes sense.

**Comment by xnieamo** [comment] 2015-06-19 17:56
I don't have any code that's particularly dependent on the cone size I believe, so either one is fine with me code wise.  I don't know which one makes more sense physically.  

I have another issue that may be related to the cone size.  I'm using the code above to test for 'pixel noise' that is a result of the images we rendered being stochastically variant.  The pixels are slightly different on each render.

What I have been doing is creating multiple sensors with different oi.  Then I calculate the norm of the difference between the images.
```
oi2 = loadOpticalImageData('PixelNoise/Standard', 'blue0L1-RGB');
s2 = coneAbsorptions(sensor, oi2);
p2 = sensorGet(s2, 'photons');

norm(p1(:) - p2(:))
```

Before the merge, the norm averaged around 1800 but is now at 2500 afterwards.  I think this may be caused if each cone has larger isomerizations now that they are bigger and the different cone mosaic.  However, I wanted to make that this is the case and nothing else was affected.

It seems that total photoisomerizations are roughly the same before and after which makes sense to me.

**Comment by hjiang36** [comment] 2015-06-25 16:38
I think we know the reason that causes this issue. Could check and change the default value in the future.
Close it for now.

**Closed by hjiang36** 2015-06-25 16:38 UTC
