### ISSUE TITLE
unit test ...

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#24] opened 2015-05-10 00:00 UTC
Asking for help from the pros, here.  I am up to date on the UnitTestToolbox and on the master branch of isetbio.  

[  1] 'v_Colorimetry'
	Internal validation  : PASSED
	Run-time status      : no exception raised
Reference to non-existent field 'generateGroundTruthDataIfNotFound'.

Error in UnitTest/validate>doFastValidation (line 388)
            if (projectSpecificPreferences.generateGroundTruthDataIfNotFound)

Error in UnitTest/validate (line 249)
                abortValidationSession = doFastValidation(obj, fastLocalGroundTruthHistoryDataFile, validationData,
                projectSpecificPreferences, smallScriptName);

Error in UnitTest.runValidationSession>validateFast (line 80)
    abortValidationSession = UnitTestOBJ.validate(vScriptsList);

Error in UnitTest.runValidationSession (line 27)
        validateFast(vScriptsList);

Error in validateFastAll (line 40)
    UnitTest.runValidationSession(vScriptsList, 'FAST');

**Comment by DavidBrainard** [comment] 2015-05-10 00:10
Did you re-run the configuration template after you updated UnitTestToolbox?  That will set the preferences that UnitTestToolbox needs.  The template is in the isetbio/validation directory.  I am pretty sure that you can use the default settings for FAST validation.


> On May 9, 2015, at 8:00 PM, Brian Wandell <notifications@github.com> wrote:
> 
> Asking for help from the pros, here. I am up to date on the UnitTestToolbox and on the master branch of isetbio.
> 
> [ 1] 'v_Colorimetry'
> Internal validation : PASSED
> Run-time status : no exception raised
> Reference to non-existent field 'generateGroundTruthDataIfNotFound'.
> 
> Error in UnitTest/validate>doFastValidation (line 388)
> if (projectSpecificPreferences.generateGroundTruthDataIfNotFound)
> 
> Error in UnitTest/validate (line 249)
> abortValidationSession = doFastValidation(obj, fastLocalGroundTruthHistoryDataFile, validationData,
> projectSpecificPreferences, smallScriptName);
> 
> Error in UnitTest.runValidationSession>validateFast (line 80)
> abortValidationSession = UnitTestOBJ.validate(vScriptsList);
> 
> Error in UnitTest.runValidationSession (line 27)
> validateFast(vScriptsList);
> 
> Error in validateFastAll (line 40)
> UnitTest.runValidationSession(vScriptsList, 'FAST');
> 
> —
> Reply to this email directly or view it on GitHub.
> 


=========
David H. Brainard
RRL Professor of Psychology
Director, Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by npcottaris** [comment] 2015-05-10 01:13
Hello Brian,

Like David said, you probably have not run the 
~~~
setIsetbioUnitTestPreferencesTemplate.m
~~~
script, or have not run it recently.

Execute 
~~~
getpref('isetbioValidation')
~~~
 to see the current preferences for the isetbioValidation project.On my computer this gives
~~~
               onRunTimeErrorBehavior: 'catchExceptionAndContinue'
                        generatePlots: 1
                      closeFigsOnInit: 1
                            verbosity: 'med'
                     numericTolerance: 1.1102e-13
                  graphMismatchedData: 0
                  compareStringFields: 0
           projectSpecificPreferences: [1x1 struct]
                          projectName: 'isetbioValidation'
                    validationRootDir: '/Users/Shared/Matlab/Toolboxes/isetbio/validation'
                 alternateFastDataDir: ''
                 alternateFullDataDir: '/Users1/Shared/Dropbox/ISETBIOFullValidationData'
                   clonedWikiLocation: '/Users/Shared/Matlab/Toolboxes/ISETBIO_Wiki/isetbio.wiki'
                clonedGhPagesLocation: '/Users/Shared/Matlab/Toolboxes/ISETBIO_GhPages/isetbio'
                        githubRepoURL: 'http://isetbio.github.io/isetbio'
    generateGroundTruthDataIfNotFound: 1
~~~
You should have generateGroundTruthDataIfNotFound = 0 after running the script named above.

Nicolas

**Comment by wandell** [comment] 2015-05-10 01:46
OK, thanks.  I reran the setIsetbioXXX as per instructions. It did in fact update the preference information.  

However, the next round was included a mkdir problem.  (I have permission and could run mkdir('foo') successfully).  Below is the diagnostic printout from validateFastAll.

After this settles, I will try to put the setIsetbioUnitTestPreferencesTemplate execution inside the validation code for some of these failure cases ... maybe a try/catch ...

Thanks,
Brian
----

UnitTest will use preferences for the 'isetbioValidation' project

A set of existing preferences for project 'isetbioValidation' was found.

Current UnitTest project is set to : 'isetbioValidation', with the following preferences:
	 'onRunTimeErrorBehavior'  : 'catchExceptionAndContinue'
	 'generatePlots'           : false
	 'closeFigsOnInit'         : true
	 'verbosity'               : 'med'
	 'numericTolerance'        : 1.11022e-13
	 'graphMismatchedData'     : false
	 'compareStringFields'     : false
	 'projectSpecificPreferences' : backup of project specific options
	 'projectName'             : 'isetbioValidation'
	 'validationRootDir'       : '/Users/wandell/GitHub/isetbio/validation'
	 'alternateFastDataDir'    : ''
	 'alternateFullDataDir'    : '/Users1/Shared/Dropbox/ISETBIOFullValidationData'
	 'clonedWikiLocation'      : '/Users/Shared/Matlab/Toolboxes/ISETBIO_Wiki/isetbio.wiki'
	 'clonedGhPagesLocation'   : '/Users/Shared/Matlab/Toolboxes/ISETBIO_GhPages/isetbio'
	 'githubRepoURL'           : 'http://isetbio.github.io/isetbio'
	 'generateGroundTruthDataIfNotFound' : false


------------------------------------------------------------------------------------------------------------
Running in 'FAST' mode with 'catchExceptionAndContinue' runtime hehavior and verbosity level = 'med'.
Will validate 15 scripts.
------------------------------------------------------------------------------------------------------------

[  1] 'v_Colorimetry'
Error using mkdir
Permission denied

Error in UnitTest/generateDirectory (line 7)
        mkdir(fullDir);

Error in UnitTest/validate (line 117)
                obj.generateDirectory(obj.fullValidationDataDir, scriptSubDirectory);

Error in UnitTest.runValidationSession>validateFast (line 80)
    abortValidationSession = UnitTestOBJ.validate(vScriptsList);

Error in UnitTest.runValidationSession (line 27)
        validateFast(vScriptsList);

Error in validateFastAll (line 40)
    UnitTest.runValidationSession(vScriptsList, 'FAST');

**Comment by npcottaris** [comment] 2015-05-10 04:30
Hello Brian,

This bug should be now fixed. Please git pull and retry.

The bug was a regression introduced by me when we decided to have synchronized generation of FAST and FULL validation data. Since you do not have FULL validation data, the program tried to generate FULL validation data during your FAST validation data run, but it did this without first checking the 'generateGroundTruthDataIfNotFound' preference. Since your FULL validation data dir was set to /Users1/ ... , which is a path to which you probably do not have write access, it bombed.

I have changed the code to check that flag now. As long as that flag is set to false, which it should for anyone not generating validation data, you should be OK. If you set that flag to true, then you must make sure that you change the FULL validation data dir to a location to which you do have write access.
The value of the FULL validation data dir is set in setIsetbioUnitTestPreferencesTemplate.m.

Nicolas

**Comment by wandell** [comment] 2015-05-10 05:40
Thanks - and don’t you have to go to bed now?

Also, don’t forget that tomorrow is Mother’s Day.  That’s important stuff.

Brian

> On May 9, 2015, at 9:30 PM, Nicolas Cottaris <notifications@github.com> wrote:
> 
> Hello Brian,
> 
> This bug should be now fixed. Please git pull and retry.
> 
> The bug was a regression introduced by me when we decided to have synchronized generation of FAST and FULL validation data. Since you do not have FULL validation data, the program tried to generate FULL validation data during your FAST validation data run, but it did this without first checking the 'generateGroundTruthDataIfNotFound' preference. Since your FULL validation data dir was set to /Users1/ ... , which is a path to which you probably do not have write access, it bombed.
> 
> I have changed the code to check that flag now. As long as that flag is set to false, which it should for anyone not generating validation data, you should be OK. If you set that flag to true, then you must make sure that you change the FULL validation data dir to a location to which you do have write access.
> The value of the FULL validation data dir is set in setIsetbioUnitTestPreferencesTemplate.m.
> 
> Nicolas
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/24#issuecomment-100581763>.
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by DavidBrainard** [comment] 2015-05-10 12:52
> After this settles, I will try to put the setIsetbioUnitTestPreferencesTemplate execution inside the validation code for some of these failure cases ... maybe a try/catch …

This isn’t a bad idea, but would need to be implemented with considerable caution to avoid really confusing situations.

For example, once someone customizes the template file, it is a good idea to keep that outside of isetbio so it doesn’t get clobbered or pushed to the repository.  Then, if something crashes for a reason unrelated to the preferences, it will reset the generic preferences which will then cause other unexpected behaviors.

If the conditional is on no preferences existing, that might be safer.  Or if the lack of preferences or error causes a useful message to be printed, that says to set the preferences … that might be a good option.

**Comment by DavidBrainard** [comment] 2015-06-29 14:57
Although this isn't really completely dealt with, how to deal with it remains unclear and I think the way we have it may be good enough for now.  I am closing.  Next time someone hits a problem trying to validate on their machine, please open a new issue describing whatever the problem is and we'll think harder with the new failure mode in mind.

**Closed by DavidBrainard** 2015-06-29 14:57 UTC
